SyntaxError print
File "/python/lib/python3.8/site-packages/chatbot.py", line 166
print 'Couldn\'t log in: Quitting.'
SyntaxError: Missing parentheses in call to 'print'.